// List of major cities in Mexico
export const mexicanCities = [
  'Acapulco',
  'Aguascalientes',
  'Cancún',
  'Cd. Juárez',
  'Chihuahua',
  'Ciudad de México',
  'Ciudad Madero',
  'Colima',
  'Córdoba',
  'Cuernavaca',
  'Culiacán',
  'Durango',
  'Ecatepec',
  'Ensenada',
  'Guadalajara',
  'Guanajuato',
  'Hermosillo',
  'Irapuato',
  'Jalapa',
  'La Paz',
  'León',
  'Los Cabos',
  'Los Mochis',
  'Matamoros',
  'Mazatlán',
  'Mérida',
  'Mexicali',
  'Minatitlán',
  'Monclova',
  'Morelia',
  'Navojoa',
  'Naucalpan',
  'Nezahualcóyotl',
  'Nuevo Laredo',
  'Oaxaca',
  'Orizaba',
  'Pachuca',
  'Pátzcuaro',
  'Piedras Negras',
  'Playa del Carmen',
  'Puebla',
  'Puerto Vallarta',
  'Querétaro',
  'Reynosa',
  'Saltillo',
  'San Luis Potosí',
  'San Nicolás de los Garza',
  'Silao',
  'Soledad de Graciano Sánchez',
  'Tapachula',
  'Temixco',
  'Tehuacán',
  'Tijuana',
  'Tlalpan',
  'Torreón',
  'Tulancingo',
  'Tultitlán',
  'Tuxtla Gutiérrez',
  'Uruapan',
  'Veracruz',
  'Victoria de Durango',
  'Villahermosa',
  'Xalapa',
  'Xalostoc',
  'Zacatecas',
  'Zapopan',
  'Zitácuaro',
]
